### PR TITLE
better css 

### PR DESCRIPTION
**Pull request by shijn**
- make snow `zindex` above default 
- prevent from annoying user select origin content

### CODE REVIEW

**Comment by HermannBjorgvin** [comment]
How is this better? Just wondering otherwise thanks for the pull will consider merging with master when I get a break from Christmas stuff :P :P: P:P ::PP:P:P: P

Cheers

**Comment by shijn** [comment]
1. `z-index` set to `1` makes snow effect it above some `absolute` positioned elements
2. `user-select:none` lets user select text, images etc. otherwise they can only click on the canvas area

**Comment by HermannBjorgvin** [comment]
Sure, merging this, I thought pointer-events=none already got the mouse click through thing though

**Comment by shijn** [comment]
I suppose `pointer-events=none` also works, while `user-select` is my own habit, first time heard abt this attribute, gotcha.

their compatibility is alike(unless IE11 on caniuse), it's safe to rm it.

**Pull request merged**
